version: '3'

services:
  markdown-epub-api:
    build: .
    ports:
      - "8080:5000"
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - DEBUG=False
    volumes:
      - ./app.py:/app/app.py  # For development
    restart: unless-stopped
